### ISSUE TITLE
Convergence of polynomial algorithm

### ISSUE THREAD

**Issue by NymanLauri** [fph/RiemannOracle#3] opened 2024-03-18 18:08 UTC
For the polynomial algorithm, ``eps`` gets too small before convergence which creates numerical problems that sometimes severely affect the quality of the output. A possible fix is to implement the augmented Lagrangian.

**Comment by fph** [comment] 2024-03-20 14:37
Thanks Lauri! Do you have a minimal example to reproduce this problem?

Just to confirm: this didn't happen with your other version of the algorithm, right?

I'm at work on implementing the augmented Lagrangian in that case, too, anyway. While I am at it, I will probably also switch to using `svd(M)` for the inversion rather than `M' / (M*M' + epsilon*eye(m+2))`; this looks like it might improve accuracy in ill-conditioned problems.

**Comment by NymanLauri** [comment] 2024-03-20 16:55
This happened with the other algorithm, `nearest_singular_polynomial.m`. `example_polynomial.m` provides an example if you increase the value of `options.max_outer_iterations` to e.g. 20.

It seems that this happens approximately when epsilon becomes lower than 1e-16. The stopping criterion currently is that the relative error in the constraint should be less than 1e-16. 

Since we know that the Frobenius norm of the constraint is bounded above by eps*norm(A,’f’’) (so the error relative to norm(A,’f’’) is bounded above by eps), would it make sense to stop the iteration just before eps becomes problematically small? Assuming we can somehow characterize this value, but for now something like eps=1e-15 would do. I guess one technical problem with this proposal is that if the constraint is not satisfied exactly, then the computed perturbation might be very far away from a perturbation that satisfies the constraint exactly, even if the constraint itself is small. 

Switching to `svd(M)` could also fix this problem, as well as implementing the augmented Lagrangian. 

I see that you have made some changes to this other version already. Miryam and I could also work on implementing these changes for this alternative algorithm.

**Comment by fph** [comment] 2024-03-20 17:23
> Since we know that the Frobenius norm of the constraint is bounded above by eps*norm(A,’f’’)

Uhm I don't see this bound immediately but maybe I am missing something.

Anyhow I confirm that getting the stopping criterion right seems tricky, even in the other problems; at a certain point the algorithm stagnates.

> I see that you have made some changes to this other version already. 

Nothing major: just defining some additional variables for readability (2k seems clearer than 4, for instance), documentation, error handling, caching the computed value of M; the algorithm itself is unchanged.

> Miryam and I could also work on implementing these changes for this alternative algorithm.

As you prefer! Both options are fine with me.

**Comment by NymanLauri** [comment] 2024-03-21 00:40
> Uhm I don't see this bound immediately but maybe I am missing something.

Ah yes, I had overlooked the fact that the norms are squared whereas eps is not. The correct bound is sqrt(eps)*norm(A,’f’) which is not that interesting.

> As you prefer! Both options are fine with me.

For the augmented Lagrangian, we had implemented a version with an incorrect cost function, but it should be easy to modify it. So maybe we can do that in the near future.

**Comment by fph** [comment] 2024-03-21 08:58
> Ah yes, I had overlooked the fact that the norms are squared whereas eps is not. The correct bound is sqrt(eps)*norm(A,’f’) which is not that interesting.

I don't see this either, I am afraid. Where does it come from?

> So maybe we can do that in the near future.

Ok! In case let me know if I can help with something. I have that case working in the Julia version, even though the code isn't very readable because it's integrated with the other implementation and uses a more "$\mathcal{T}(A)$-oriented" approach. But I have already had to figure out some parts of it.

In the meantime, I still have some work to do on `nearest_singular_structured_dense.m`, I would like to change the implementation a little to use the thin SVD even in the case when M is tall-thin, and I have to figure out the best way to do it.

**Comment by NymanLauri** [comment] 2024-03-21 14:42
> I don't see this either, I am afraid. Where does it come from?

The idea is that

min ||delta||^2 + 1/eps * ||constraint||^2 <= ||A||^2 

since the choice for delta that corresponds to -A yields the right hand side. Then, rearranging the terms yields that bound for ||constraint||^2. This assumes that A can be represented with the structure that we impose on the problem.

> Ok! In case let me know if I can help with something. I have that case working in the Julia version, even though the code isn't very readable because it's integrated with the other implementation and uses a more "$\mathcal{T}(A)$-oriented" approach. But I have already had to figure out some parts of it.

We'll look into it and let you know how it goes!

> In the meantime, I still have some work to do on `nearest_singular_structured_dense.m`, I would like to change the implementation a little to use the thin SVD even in the case when M is tall-thin, and I have to figure out the best way to do it.

Perfect!

**Comment by NymanLauri** [comment] 2024-03-24 18:11
The augmented Lagrangian is now implemented for the non-structured polynomial algorithm (without support for the exact Hessian at the moment). However, the convergence is slow as demonstrated by `example_polynomial.m`. It is unclear to us what the reason for this behaviour could be (or if this is to be expected?). Right now, it seems that the regularized non-Lagrangian version works better. We did not switch to `svd(M)` yet.

**Comment by fph** [comment] 2024-03-25 08:39
It seems that the current implementation fails `checkgradient`:
```
example_polynomial
regproblem = apply_regularization(problem, 0.1, randn(n,d+3));
checkgradient(regproblem)
The slope should be 2. It appears to be: 1.
If it is far from 2, then directional derivatives might be erroneous.
The residual should be 0, or very close. Residual: 7.20876e-15.
```
I guess that's the reason. I'll check more thoroughly though. It fails also on an example with real coefficients, so that's not just a conjugation issue.

If you test on a real-valued example, I can also compare with the Julia implementation; the details and parameters of the algorithm are not going to be the same, but hopefully the general behavior is similar. For that implementation, I also seem to recall that `trustregions` worked so-so without the exact Hessian, and BFGS was faster in the end; but with the Hessian the picture changed.

**Comment by fph** [comment] 2024-03-25 08:48
I committed a quick fix https://github.com/fph/NearestUnstableMatlab/commit/d01efd646a4165aac1e625ee8ca561f5581546f2 , now `checkgradient` works. Iterations-wise, the algorithm still seems a little slower, but maybe we should test more carefully since the method doesn't  take enough iterations to reach convergence (in the sense of constraint=0).

**Comment by fph** [comment] 2024-03-26 12:05
I made some small changes to `nearest_singular_polynomial.m`, in https://github.com/fph/NearestUnstableMatlab/commit/0abfa04fc945ac62822997d088784704d8f7c2f0, mostly to use `r` in place of `-Av`, and now the Hessian seems to be ok also with a nonzero `y`: it passes the `checkhessian` test. The example `example_polynomial.m` is now faster, but still the residual does not converge to zero as I hoped. Still some work to do.

**Comment by NymanLauri** [comment] 2024-03-26 18:17
Thanks for looking into this!

It seems that there were two places where the term `eps*y` was missing. Thanks for spotting / fixing this. Like you said, there’s still work to do in getting it to converge.

**Comment by fph** [comment] 2024-03-27 09:19
It seems that if one changes some parameters (remove the 4 seconds limit, do 30 outer iterations rather than 10) the method converges to a feasible solution; but I haven't compared its accuracy to other methods. So it seems that we are on the correct route.

I think I am finished with refactoring the code to use `svd(M)` in the other files; now I can do it in the polynomial case, too: this seems doable, but I will need to refactor the formulas a little: by analogy with the other methods, it should be possible to reshuffle the computation to solve only two linear systems with $MM^* + \varepsilon I$, rather than computing an explicit inverse.

I'll try to make this change today if I manage!

**Closed as completed** 2024-04-30 15:03 UTC
